#!/usr/bin/env sh
set -eu
exec 2>&1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo 'Waiting for services to stop...'
sv -w196 force-stop $SERVICE_ENABLED_DIR/*
sv exit $SERVICE_ENABLED_DIR/*

# kill any other processes still running in the container
for ORPHAN_PID in $(ps --no-headers -eo "%p," -o stat | tr -d ' ' | grep 'Z' | cut -d',' -f1); do
    timeout 5 /bin/sh -c "kill $ORPHAN_PID && wait $ORPHAN_PID || kill -9 $ORPHAN_PID"
done
